config/routes.rb
Rails.application.routes.draw do
  # resources :stocks
  devise_for :users
  get 'home/index'
  root to: 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/' => 'home#index'

  resources :stocks
  post 'stocks/:id/', to: 'stocks#update'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:id] == ''
      @nothing = "Hey, you forgot to enter a symbol"
    elsif
      if params[:id]
        @stock = StockQuote::Stock.quote(params[:id])
          if @stock == nil || @stock.name == nil
            @error = 'That is not a valid stock symbol'
          end
      end
    end
end

  def about
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = current_user.stocks
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
    @stock = Stock.find_by_id(params[:id])
    @stock_quote = StockQuote::Stock.quote(@stock.ticker)
    @stock_history = StockQuote::Stock.history(@stock.ticker, start_date, end_date)
    # get_stock_history
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)
    @stock.user_id = current_user.id
    @stock.sname = StockQuote::Stock.quote(params['stock'][:ticker]).sname
    @stock.name = StockQuote::Stock.quote(params['stock'][:ticker]).name
    respond_to do |format|
      if @stock.save
        format.html { redirect_to stocks_path, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        # render 'new'
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id, :shares, :sname, :name, :start_date, :end_date)
    end
    def correct_user
      @ticker = current_user.stocks.find_by(id: params[:id])
      redirect_to stocks_path, notice: "Not authorized to edit this stock" if @ticker.nil?
    end
    def get_stock_history(ticker, start_date, end_date)
     @stock_history = StockQuote::Stock.history(ticker, start_date, end_date)
        @stock_price_hash = {}
        @stock_history[:history].each do |day|
          @stock_price_hash[day[:date]] = day[:close]
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible">
    <button class="close" data-dismiss="alert">
      <i class="glyphicon glyphicon-remove-circle"></i>
    </button>
      <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=   link_to "Stock App", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%=   link_to "Home", root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Stocks", stocks_path %></li>
          <li><%= link_to "Add a Stock", new_stock_path %></li>
          <li><%= link_to "Edit User Profile", edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About</h1>
<p>My Stocks</p>

app/views/home/index.html.erb
<%= form_tag root_path, method: 'post' do %>
  <div class="form-group">
    <%= text_field_tag 'id', nil, placeholder: "Enter Company Ticker Symbol", size: 50, class: "form-control" %>
    <%= submit_tag "Look up" , class: "btn btn-danger"%>

  </div>
<% end %>

<br>
<% if @stock %>
  <div class="row">
    <div class="col-md-6">
      <%= @stock.name %> <br>
      <%= @stock.symbol %> <br>
      <%= @stock.op %> <br>
      <%= @stock.eps %> <br>
      <%= @stock.exchange %> <br>
      <%= @stock.beta %> <br>
      <%= @stock.sname %> <br>
      <%= @stock.l.to_f %>
    </div>
    <div class="col-md-6">
      <% @stock.management.each do |m| %>
        <%= m['name'] %> | <%= m['title'] %>
        <br>
        <% end %>
    </div>
    <div class="col-md-6">
      <%= @stock.name %> <br>
      <%= @stock.symbol %> <br>
      <%= @stock.op %> <br>
      <%= @stock.eps %> <br>
      <%= @stock.exchange %> <br>
      <%= @stock.beta %> <br>
      <%= @stock.sname %> <br>
      <%= @stock.l.to_f %>
    </div>
  </div>



  <%# @stock.moreresources%>
      <br>
      <% x = @stock.financials[0]['f_figures'].map {|x| x['recent_quarter'] }.map.with_index {|y,i| y if i == 2 || i == 3 || i ==4 }.compact %>
<%= @stock.exchange %>
<br>
<br>
  <%= @stock.f_reuters_url %>
<br>
<%# @stock.f_recent_quarter_date %>
<%# @stock.f_annlyal_date %>
<%# @stock.f_ttm_date %>
<%# @stock.financials %>
<br>
<%= @stock.pe %>
<br>
<%= @stock.vo %>
<br>
<%= @stock.iname %>
<br>



<%= @stock.mc %>

<%= @stock.fwpe %>
<%= @stock.beta %>
<%= @stock.eps %>
<%= @stock.dy %>
<%= @stock.ldiv %>
<%= @stock.shares %>
<%= @stock.instown %>
<%= @stock.eo %>
<%= @stock.sid %>
<%= @stock.iid %>
<%= @stock.iname %>

  <%# @stock.related %>
<%# @stock.summary %>
<%# @stock.events%>

<% elsif @nothing %>
  <%= @nothing %>
<% elsif @error %>
  <%= @error %>
<% end  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>

  <body>
    <%= render 'home/navbar'%>
  <div class="container">
    <%= render 'home/flash' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/stocks/_date.html.erb
<%= form_for @stock, :remote => true do |f| %>
  <div class="field">
    <%= f.hidden_field :stock_id, :value => @stock.id %>
    <%= f.date_field :start_date, :value => @stock.start_date %>
    <%= f.date_field :end_date, :value => @stock.end_date %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

<% @stock_history = StockQuote::Stock.history(@stock.ticker,   @stock.start_date ||= "10/22/2017",  @stock.end_date ||="12/20/2107") %>
  <% @stock_price_hash = {} %>
  <% @stock_history[:history].each do |day| %>
    <% @stock_price_hash[day[:date]] = day[:close] %>
  <% end %>
<%= line_chart (@stock_price_hash), xtitle: "Date", ytitle: "Price", height: "500px"  %>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |f| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :ticker %> <br>
    <%= f.text_field :ticker, id: :stock_ticker %>
  </div>
  <div class="form-group">
    <%= f.label :shares %> <br>
    <%= f.number_field :shares, min: 1 %>
  </div>
  
  <div class="actions">
    <%= f.submit "Add stock", class: "btn btn-success" %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h3> My Portfolio</h3>
  <% if @stocks.empty? %>
    <h2> <%= "Buy some stocks!!" %> </h2>
  <% end %>

    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>Company Name</th>
          <th>Ticker</th>
          <th>Shares</th>
          <th>Sector</th>
          <th>Current Price</th>
          <th>Market Value</th>
        </tr>
      </thead>

      <tbody>
        <% @total_mv = 0 %>
        <% @stocks.each do |stock| %>
            <% @stock_quote = StockQuote::Stock.quote(stock.ticker) %>
          <tr>
              <td><%= link_to @stock_quote.name, stock %></td>
              <td><%= stock.ticker.upcase %></td>
              <td><%= stock.shares %></td>
              <td><%= stock.sname %></td>
              <td><%= @stock_quote.l %></td>
                  <% @market_value = (stock.shares * @stock_quote.l.gsub(/[^\d^\.]/, '').to_f)%>
              <td> <%= number_to_currency(@market_value) %></td>
                  <% @total_mv += @market_value %>
            </tr>
        <% end %>

      </tbody>
    </table>
        <%= number_to_currency(@total_mv) %>
<br>

<%= link_to 'Add a Stock', new_stock_path, class: 'btn btn-default' %>
<%# color = [] %>

<%# 6.times do %>
  <%# color.push('#' + "%06x" % (rand * 0xffffff)) %>
<%# end %>

<%# color %>
<div class="row">
    <div class="col-md-6">
      <%= pie_chart @stocks.group(:name).sum(:shares) %>
    </div>

    <div class="col-md-6">
      <%= pie_chart @stocks.group(:sname).sum(:shares) %>
    </div>

  </div>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><h3><strong><%= @stock_quote.name %> | <%= @stock_quote.symbol %></strong></h3>
    </div>
    <div class="panel-body">
      <div class="col-md-4">
        <% if @stock_quote.c.to_f >= 0 %>
          <h1 class='green'><%= @stock_quote.l %></h1> <br>
          <strong>Days Change: </strong><em class='green'><%= @stock_quote.c %> </em><br>
        <% else %>
          <h1 class='red'><%= @stock_quote.l %></h1> <br>
          <strong>Days Change: </strong> <em class='red'><%= @stock_quote.c %> </em> <br>
        <% end %>

        <strong>Current Company Worth: </strong><%= @stock_quote.mc %> <br>
        <strong>52 Week High: </strong><%= @stock_quote.hi52 %> <br>
        <strong>52 Week Low:</strong><%= @stock_quote.lo52 %> <br>
      </div>
      <div class="col-md-8">
        <%= @stock_quote.summary[0]['overview'] %>
      </div>
    </div>
  </div>
  <div class="panel-footer">
      <%= link_to 'Edit', edit_stock_path(@stock), class: 'btn btn-default'  %>
      <%= link_to 'Back', stocks_path, class: 'btn btn-default' %>
      <%= link_to 'Remove Stock', stock_path(@stock), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
  </div>
<%=  %>

<br>

<%#= Price chart tabs  %>

<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="mtd-tab" data-toggle="tab" href="#mtd" role="tab" aria-controls="mtd" aria-selected="true">MTD</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="ytd-tab" data-toggle="tab" href="#ytd" role="tab" aria-controls="ytd" aria-selected="false">YTD</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="3y-tab" data-toggle="tab" href="#3y" role="tab" aria-controls="3y" aria-selected="false">3Y</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="5y-tab" data-toggle="tab" href="#5y" role="tab" aria-controls="5Y" aria-selected="false">5Y</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="custom-tab" data-toggle="tab" href="#custom" role="tab" aria-controls="custom" aria-selected="false">Custom</a>
  </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane active" id="mtd" role="tabpanel" aria-labelledby="mtd-tab">
    <% @stock_history = StockQuote::Stock.history(@stock.ticker, Date.today.beginning_of_month, Date.today) %>
      <% @stock_price_hash = {} %>
        <% @stock_history[:history].each do |day| %>
        <% @stock_price_hash[day[:date]] = day[:close] %>
      <% end %>
      <%= line_chart (@stock_price_hash), xtitle: "Date", ytitle: "Price", height: "500px"  %>
  </div>
  <div class="tab-pane" id="ytd" role="tabpanel" aria-labelledby="ytd-tab">
    <% @stock_history = StockQuote::Stock.history(@stock.ticker, Date.today.beginning_of_year, Date.today) %>
      <% @stock_price_hash = {} %>
      <% @stock_history[:history].each do |day| %>
        <% @stock_price_hash[day[:date]] = day[:close] %>
        <% end %>
      <%= line_chart (@stock_price_hash), xtitle: "Date", ytitle: "Price", height: "500px"  %>
  </div>
  <div class="tab-pane" id="3y" role="tabpanel" aria-labelledby="3y-tab">
    <% @stock_history = StockQuote::Stock.history(@stock.ticker,  Date.today.years_ago(3),  Date.today) %>
      <% @stock_price_hash = {} %>
      <% @stock_history[:history].each do |day| %>
        <% @stock_price_hash[day[:date]] = day[:close] %>
      <% end %>
      <%= line_chart (@stock_price_hash), xtitle: "Date", ytitle: "Price", height: "500px"  %>
  </div>
  <div class="tab-pane" id="5y" role="tabpanel" aria-labelledby="5y-tab">
    <% @stock_history = StockQuote::Stock.history(@stock.ticker,   Date.today.years_ago(5),  Date.today) %>
      <% @stock_price_hash = {} %>
      <% @stock_history[:history].each do |day| %>
        <% @stock_price_hash[day[:date]] = day[:close] %>
      <% end %>
      <%= line_chart (@stock_price_hash), xtitle: "Date", ytitle: "Price", height: "500px"  %>
  </div>
  <div class="tab-pane" id="custom" role="tabpanel" aria-labelledby="custom-tab">
      <%= render 'date' %>
  </div>
</div>